// TEST
export const TEST_DISPATCH = "TEST_DISPATCH";

// GET ERROR
export const GET_ERRORS = "GET_ERRORS";

// SET current user
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// GET PROFILE
export const GET_PROFILE = "GET_PROFILE";

// PROFILE LOADING
export const PROFILE_LOADING = "PROFILE_LOADING";

// PROFILE NOT FOUND
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";

// CLEAR CURRENT PROFILE
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

// GET PROFILES
export const GET_PROFILES = "GET_PROFILES";
